org: odiaz
app: apollo-lambda
service: apollo-lambda-ours-1
provider:
  name: aws
  runtime: nodejs14.x
plugins:
  - serverless-offline
functions:
  graphql:
    handler: dist/index.handler
    events:
      - http:
          path: /graphql
          method: GET
          cors: true
      - http:
          path: /graphql
          method: POST
          cors: true